TREE_TOP = ${HOME}/magicleap
KERNEL_TOP = ${TREE_TOP}/kernel
HYDRA_TOP = ${TREE_TOP}/hydra_modules

obj-m += hydra.o

hydra-y += hydra_drv.o hsi.o nwl.o vcam.o wearable.o

# for cvip
ccflags-y += -I${src}
ccflags-y += -I$(KERNEL_TOP)/drivers/staging/cvip/dcprs
ccflags-y += -I$(KERNEL_TOP)/include/linux/cvip
ccflags-y += -I$(KERNEL_TOP)/include/linux/cvip/hydra
ccflags-y += -I$(KERNEL_TOP)/drivers/staging/android

# KBUILD_EXTRA_SYMBOLS  = ${AMD_OUT_KERNEL}/Module.symvers
